#!/usr/bin/env bash

if [[ "$IFACE" == "template" ]]
then
  phy="phy-$IFACE"
  ovs="ovs-$IFACE"
  if [[ "$MODE" == "start" ]]
  then
    echo "Creating veth pair: $phy <-> $ovs"
    ip link add name "$phy" type veth peer name "$ovs"
    ip link set "$phy" up
    ip link set "$ovs" up
  elif [[ "$MODE" == "stop" ]]
  then
    echo "Deleting veth pair: $phy <-> $ovs"
    ip link del "$phy"
  fi
fi
